### ISSUE TITLE
Error: MultipartUploadError

### ISSUE THREAD

**Issue by coltoneshaw** [electron/electron-notarize#104]
macOS Monterey 12.13.1

When attempting to notarize I get the below error. This same script has worked in the past without fail. The package exists and all variables are set. I cannot find additional guidance online for this. 

```bash
% node scripts/notarize.js                                                 
{
  code: 1,
  output: 'Error: MultipartUploadError(error: HTTPClientError.readTimeout, completedParts: [])\n'
}
/node_modules/electron-notarize/lib/notarytool.js:94
        throw new Error(`Failed to notarize via notarytool\n\n${result.output}`);
              ^

Error: Failed to notarize via notarytool

Error: MultipartUploadError(error: HTTPClientError.readTimeout, completedParts: [])

    at Object.<anonymous> (node_modules/electron-notarize/lib/notarytool.js:94:15)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/electron-notarize/lib/notarytool.js:4:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
% 
```

**Comment by coltoneshaw** [comment]
It seems that I can notarize it myself via the command without an error. So, I'm curious if it's something with how this package uploads it. 

```bash
xcrun altool --notarize-app -f path/app.zip --primary-bundle-id "com.app" -u email@email.com -p password --team-id teamID
```

**Comment by coltoneshaw** [comment]
Looks like updating electron-notarize fixed the problem
