### ISSUE TITLE
Error: Failed to upload app to Apple's notarization servers

### ISSUE THREAD

**Issue by wenbinobject** [electron/electron-notarize#24]
Error: Failed to upload app to Apple's notarization servers

2019-11-12 15:26:51.464 altool[63763:2512756]  Error:
[2019-11-12 15:26:51 CST] <main>  INFO: An error occurred downloading: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/2.0.0/bundles/org.xerial.sqlite-jdbc-3.27.2.1.jar Connection reset Exception's name: java.net.SocketException, Exception's message: Connection reset

I look at this function，
    const notarizeArgs = [
      'altool',
      '--notarize-app',
      '-f',
      zipPath,
      '--primary-bundle-id',
      opts.appBundleId,
      ...authorizationArgs(opts),
    ];

    if (opts.ascProvider) {
      notarizeArgs.push('-itc_provider', opts.ascProvider);
    }

    const result = await spawn('xcrun', notarizeArgs);
    if (result.code !== 0) {
      throw new Error(`Failed to upload app to Apple's notarization servers\n\n${result.output}`);
    }
export const spawn = (
  cmd: string,
  args: string[] = [],
  opts: SpawnOptions = {},
): Promise<SpawnResult> => {
  d(
    'spawning cmd:',
    cmd,
    'args:',
    args.map(arg => (isSecret(arg) ? '*********' : arg)),
    'opts:',
    opts,
  );
  const child = cpSpawn(cmd, args, opts);
  const out: string[] = [];
  const dataHandler = (data: Buffer) => out.push(data.toString());
  child.stdout!.on('data', dataHandler);
  child.stderr!.on('data', dataHandler);
  return new Promise<SpawnResult>(resolve => {
    child.on('exit', code => {
      d(`cmd ${cmd} terminated with code: ${code}`);
      resolve({
        code,
        output: out.join(''),
      });
    });
  });
};

I don't know how this could happen，What should I do。

**Comment by wenbinobject** [comment]
Error: Failed to upload app to Apple's notarization servers

2019-11-12 15:50:15.839 altool[64325:2528829] Using the proxy host '127.0.0.1' for delivery.
2019-11-12 15:50:15.841 altool[64325:2528829] Using the proxy port '1086' for delivery.
2019-11-12 15:50:16.573 altool[64325:2528829]  Error:
[2019-11-12 15:50:16 CST] <main>  INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
[2019-11-12 15:50:16 CST] <main>  INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
[2019-11-12 15:50:16 CST] <main>  INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
[2019-11-12 15:50:16 CST] <main>  INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server

**Comment by bkniffler** [comment]
Check https://appstoreconnect.apple.com/ and login, maybe you need to review your contracts.

**Comment by 1000111001** [comment]
> Error: Failed to upload app to Apple's notarization servers
> 
> 2019-11-12 15:50:15.839 altool[64325:2528829] Using the proxy host '127.0.0.1' for delivery.
> 2019-11-12 15:50:15.841 altool[64325:2528829] Using the proxy port '1086' for delivery.
> 2019-11-12 15:50:16.573 altool[64325:2528829] Error:
> [2019-11-12 15:50:16 CST]
> 
> INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
> [2019-11-12 15:50:16 CST] INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
> [2019-11-12 15:50:16 CST] INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server
> [2019-11-12 15:50:16 CST] INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml Unexpected end of file from server Exception's name: java.net.SocketException, Exception's message: Unexpected end of file from server

same issue, the follow works for me
https://stackoverflow.com/questions/58602492/an-error-occurred-delivering-to-the-app-store

**Comment by lifestep** [comment]
Maybe failed in 2-step verification, you can get Application key from account setting to try it again

**Comment by andreineculau** [comment]
Also make sure that `xcrun altool --help` lists `apiKey` as a possible argument for instance. We were not paying attention to it, but our version of `altool` was too old, didn't know about `apiKey` and didn't complain about it either - it would just fail with no reason.

**Comment by polx** [comment]
For the sake of the record, I had a similar thing which was pretty impressive: one of our videos was qualified to have an inappropriate voice (broken or something such)... notarization started working once I removed the pictures and videos!

**Comment by andresreibel** [comment]
Check notarization servers:

https://www.apple.com/support/systemstatus/ 
https://developer.apple.com/system-status/

**Comment by loveheenavasu** [comment]
Hi,
Please help me I am facing the following Issue.
I am provided AppleId and Apple Password in notarize.js
⨯ Failed to upload app to Apple's notarization servers

2023-04-07 10:09:08.768 *** Error: Notarization failed for '/var/folders/1r/58vdfc6x7hjd9rh10qg5c2vm0000gn/T/electron-notarize-xKx5lc/OpenSearch by SEO Blueprint.zip'.
2023-04-07 10:09:08.770 *** Error: Unable to upload your app for notarization. Failed to get authorization for username 'lovetrivedi@iCloud.com' and password. (
    "Error Domain=NSCocoaErrorDomain Code=0 \"Status code: 0\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}"
) (-1011)
 {
    NSLocalizedDescription = "Unable to upload your app for notarization.";
    NSLocalizedFailureReason = "Failed to get authorization for username 'lovetrivedi@iCloud.com' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)";
}
  failedTask=build stackTrace=Error: Failed to upload app to Apple's notarization servers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2023-04-07 10:09:08.768 *** Error: Notarization failed for '/var/folders/1r/58vdfc6x7hjd9rh10qg5c2vm0000gn/T/electron-notarize-xKx5lc/OpenSearch by SEO Blueprint.zip'.
2023-04-07 10:09:08.770 *** Error: Unable to upload your app for notarization. Failed to get authorization for username 'lovetrivedi@iCloud.com' and password. (
    "Error Domain=NSCocoaErrorDomain Code=0 \"Status code: 0\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}"
) (-1011)
 {
    NSLocalizedDescription = "Unable to upload your app for notarization.";
    NSLocalizedFailureReason = "Failed to get authorization for username 'lovetrivedi@iCloud.com' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)";
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  at Object.<anonymous> (/Users/zestgeek-41/Documents/Electron/detailed-serp-main/node_modules/electron-notarize/src/legacy.ts:67:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zestgeek-41/Documents/Electron/detailed-serp-main/node_modules/electron-notarize/lib/legacy.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
zestgeek-41@Zestgeek-41s-MacBook-Air detailed-serp-main %

**Comment by Nguyentien193** [comment]
⨯ Failed to upload app to Apple's notarization servers
 
Error:
[2024-04-12 09:10:42 ICT] <main>  INFO: Configuring logging...
[2024-04-12 09:10:42 ICT] <main>  INFO: Logging level set to eXtreme
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: initializing data center locking ops: [authenticateForSession, validateAssets]
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: initializing data centers with: [contentdelivery01.itunes.apple.com, contentdelivery02.itunes.apple.com]
[2024-04-12 09:10:47 ICT] <main>  INFO: iTMSTransporter : iTunes Store Transporter [3.3.0]
[2024-04-12 09:10:47 ICT] <main>  INFO: OS identifier: Mac OS X 11.7.8 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
[2024-04-12 09:10:47 ICT] <main>  INFO: Memory: [JVM] 994M free, 1024M total, 2048M max [System] (Physical) 354M free, 8192M total (Swap) 1223M free, 2048M total
[2024-04-12 09:10:47 ICT] <main>  INFO: Client: altool 4.050 (1210)
[2024-04-12 09:10:47 ICT] <main>  INFO: Upload mode selected.
[2024-04-12 09:10:47 ICT] <main> DBG-X: Memory: [JVM] 982M free, 1024M total, 2048M max [System] (Physical) 344M free, 8192M total (Swap) 1223M free, 2048M total
[2024-04-12 09:10:47 ICT] <main> DBG-X: Using operation named: authenticateForTransportDiscovery
[2024-04-12 09:10:47 ICT] <main> DBG-X: Apple's web service operation input parameters:
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter Application = iTMSTransporter
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter BaseVersion = 2.1.0
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter Client = altool
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter ClientVersion = 4.050 (1210)
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter IncludeProviderPublicId = true
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter ItcProviderName = H2YSZXYGNP
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 11.7.8 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2024-04-12T09:10:47+07:00
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.127155845
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter TransporterArguments = -m upload -u admin@hitobase.io -vp json -DTxHeaders=eyJqZW5nYSI6dHJ1ZX0= -sessionid @env:9B830AD9-31C3-46EA-9935-B3BF36593ED1 -sharedsecret **hidden value** -itc_provider H2YSZXYGNP -f /var/folders/kc/nbx3vzd173q_hhmdktj3y_sw0000gn/T/A23C2CAD-43DF-4249-8513-78D34CC73955/io.hitobase.onechat.itmsp -indicator true -v eXtreme -Dtransporter.client=altool -Dtransporter.client.version=4.050 (1210)
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter Version = 3.3.0
[2024-04-12 09:10:47 ICT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2024-04-12 09:10:47 ICT] <main>  INFO: id = 20240412091047-891
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: getCurrent(); current data center is null
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: getCurrent(); iterator was null, setting it
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: getCurrent(); setting current data center to: contentdelivery01.itunes.apple.com
[2024-04-12 09:10:47 ICT] <main>  INFO: iTMSTransporter Correlation Key: 296ee626-af9a-4701-9219-0cb7f38ed787-0001
[2024-04-12 09:10:47 ICT] <main> DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery01.itunes.apple.com
[2024-04-12 09:10:48 ICT] <main> DBG-X: Apple's web service operation return value:
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter PreferredTransports = [HTTP, Signiant, Aspera]
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter TransportHosts.Signiant = [sgr602.apple.com:44001, sgr601.apple.com:44001, sgr603.apple.com:44001, sgr604.apple.com:44001]
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter SessionExpiration = 2024-04-16T02:10:48.622Z
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter TransportHosts.Aspera = [vgr502.apple.com:33001, vgr503.apple.com:33001, vgr501.apple.com:33001, vgr504.apple.com:33001]
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[2024-04-12 09:10:48 ICT] <main>  INFO: Transporter's command line arguments are: -m upload -u admin@hitobase.io -vp json -DTxHeaders=eyJqZW5nYSI6dHJ1ZX0= -sessionid @env:9B830AD9-31C3-46EA-9935-B3BF36593ED1 -sharedsecret **hidden value** -itc_provider H2YSZXYGNP -f /var/folders/kc/nbx3vzd173q_hhmdktj3y_sw0000gn/T/A23C2CAD-43DF-4249-8513-78D34CC73955/io.hitobase.onechat.itmsp -indicator true -v eXtreme -Dtransporter.client=altool -Dtransporter.client.version=4.050 (1210)
[2024-04-12 09:10:48 ICT] <main>  INFO: Gathering the list of valid files from the package ...
[2024-04-12 09:10:48 ICT] <main> DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
[2024-04-12 09:10:48 ICT] <main> DEBUG:   OneChat-beta-test.zip will be verified by Apple's web service to determine if it is a valid file.
[2024-04-12 09:10:48 ICT] <main>  INFO: Finished gathering the list of valid files from the package.
[2024-04-12 09:10:48 ICT] <main>  INFO: Examining the package at: /var/folders/kc/nbx3vzd173q_hhmdktj3y_sw0000gn/T/A23C2CAD-43DF-4249-8513-78D34CC73955/io.hitobase.onechat.itmsp
[2024-04-12 09:10:48 ICT] <main>  INFO: Ensuring that package has well formed metadata file...
[2024-04-12 09:10:48 ICT] <main> DEBUG: Getting case-sensitive metadata xml filename...
[2024-04-12 09:10:48 ICT] <main> DEBUG:   Case-sensitive metadata filename is: metadata.xml
[2024-04-12 09:10:48 ICT] <main>  INFO: JSON:{"msg":{"phase":"Upload","description":"Analyzing metadata","index":0},"messageType":"VerifyProgress"}
[2024-04-12 09:10:48 ICT] <main>  INFO: Performing authentication of package io.hitobase.onechat.itmsp ...
[2024-04-12 09:10:48 ICT] <main> DBG-X: Memory: [JVM] 964M free, 1024M total, 2048M max [System] (Physical) 330M free, 8192M total (Swap) 1223M free, 2048M total
[2024-04-12 09:10:48 ICT] <main>  INFO: JSON:{"msg":{"phase":"Upload","count":2,"description":"Analyzing metadata","index":1},"messageType":"VerifyProgress"}
[2024-04-12 09:10:48 ICT] <main> DBG-X: Deflated 542 bytes to 428
[2024-04-12 09:10:48 ICT] <main> DBG-X: Using operation named: validateMetadata
[2024-04-12 09:10:48 ICT] <main> DBG-X: Apple's web service operation input parameters:
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter Application = iTMSTransporter
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter BaseVersion = 2.1.0
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter Client = altool
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter ClientVersion = 4.050 (1210)
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter Files = [metadata.xml, OneChat-beta-test.zip]
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter IncludeProviderPublicId = true
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter ItcProviderName = H2YSZXYGNP
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
<package version="software5.9" xmlns="[http://apple.com/itunes/importer">](http://apple.com/itunes/importer%22%3E)
<software_assets
        app_platform="osx"
        primary_bundle_identifier="io.hitobase.onechat">
<asset type="developer-id-package">
<data_file>
<file_name>OneChat-beta-test.zip</file_name>
<checksum type="md5">b6eac6e8e5cfe6805ea9ad92897fc1f6</checksum>
<size>175633246</size>
</data_file>
</asset>
</software_assets>
</package>
 
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter MetadataChecksum = 368083be977b5bb1796753d43f71bb39
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter MetadataCompressed = (suppressed)
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter MetadataInfo = {app_platform=osx, primary_bundle_identifier=io.hitobase.onechat, device_id=, bundle_identifier=, packageVersion=software5.9, apple_id=, asset_types=[developer-id-package], bundle_version=, bundle_short_version_string=}
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter OSIdentifier = Mac OS X 11.7.8 (x8*** Error: Unable to notarize app.
*** Error: Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (4200) (4200)
6_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter PackageName = io.hitobase.onechat.itmsp
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter PackageSize = 175633788
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2024-04-12T09:10:48+07:00
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter TransporterArguments = -m upload -u admin@hitobase.io -vp json -DTxHeaders=eyJqZW5nYSI6dHJ1ZX0= -sessionid @env:9B830AD9-31C3-46EA-9935-B3BF36593ED1 -sharedsecret **hidden value** -itc_provider H2YSZXYGNP -f /var/folders/kc/nbx3vzd173q_hhmdktj3y_sw0000gn/T/A23C2CAD-43DF-4249-8513-78D34CC73955/io.hitobase.onechat.itmsp -indicator true -v eXtreme -Dtransporter.client=altool -Dtransporter.client.version=4.050 (1210)
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter Version = 3.3.0
[2024-04-12 09:10:48 ICT] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2024-04-12 09:10:48 ICT] <main>  INFO: id = 20240412091048-058
[2024-04-12 09:10:48 ICT] <main>  INFO: iTMSTransporter Correlation Key: 296ee626-af9a-4701-9219-0cb7f38ed787-0001
[2024-04-12 09:10:48 ICT] <main> DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery01.itunes.apple.com
[2024-04-12 09:10:49 ICT] <main> DBG-X: Apple's web service operation return value:
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter Errors = [Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (4200)]
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter RestartClient = false
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter ErrorCode = 4200
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter ErrorMessage = Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (4200)
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[2024-04-12 09:10:49 ICT] <main> DBG-X:   parameter Success = false
[2024-04-12 09:10:49 ICT] <main> ERROR: Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (4200)
[2024-04-12 09:10:49 ICT] <main> DBG-X: The error code is: 4200
[2024-04-12 09:10:49 ICT] <main>  INFO: JSON:{"msg":{"phase":"Upload","count":2,"description":"Operation failed","index":2},"messageType":"VerifyProgress"}
[2024-04-12 09:10:49 ICT] <main> DBG-X: Returning 1
 
Out:
 
 
Package Summary:
1 package(s) were not uploaded because they had problems:
        /var/folders/kc/nbx3vzd173q_hhmdktj3y_sw0000gn/T/A23C2CAD-43DF-4249-8513-78D34CC73955/io.hitobase.onechat.itmsp - Error Messages:
                Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (4200)
 
  failedTask=build stackTrace=Error: Failed to upload app to Apple's notarization servers
