### ISSUE TITLE
Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command

### ISSUE THREAD

**Issue by damianobarbati** [electron/electron-notarize#25]
Did anyone incur into the following error?

```
Package Summary:

1 package(s) were not uploaded because they had problems:
	/var/folders/dw/bb3vx0757nzckp2t81shwk6h0000gn/T/F1F8613D-3584-487D-BF3D-A8CB736639CF/net.company-name.tav.itmsp - Error Messages:
		Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)
2019-11-13 16:26:01.610 altool[27318:239676] *** Error: Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)

    at /Users/damians/Desktop/tav-client/node_modules/electron-notarize/src/index.ts:83:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/damians/Desktop/tav-client/node_modules/electron-notarize/lib/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5

```

I'm using the following script:
```javascript
const fs = require('fs');
const path = require('path');
const electron_notarize = require('electron-notarize');
const { build: { appId } } = require('./package.json');

module.exports = async function (params) {
    // Only notarize the app on Mac OS only.
    if (process.platform !== 'darwin') {
        return;
    }
    console.log('afterSign hook triggered', params);

    let appPath = path.join(params.appOutDir, `${params.packager.appInfo.productFilename}.app`);
    if (!fs.existsSync(appPath)) {
        throw new Error(`Cannot find application at: ${appPath}`);
    }

    console.log(`Notarizing ${appId} found at ${appPath}`);

    try {
        await electron_notarize.notarize({
            appBundleId: appId,
            appPath: appPath,
            appleId: process.env.appleId,
            appleIdPassword: process.env.appleIdPassword,
        });
    }
    catch (error) {
        console.error(error);
    }

    console.log(`Done notarizing ${appId}`);
};
```

**Comment by damianobarbati** [comment]
Hey guys, I solved by fighting with apple developer account / teams / passwords / licenses.

What a mess.

**Comment by mitchdennett** [comment]
@damianobarbati Can you share how you fixed this? 

I'm getting the same error

**Comment by damianobarbati** [comment]
@mitchdennett sign into your developer account (you must be the all-mighty team agent, not team admin) and accept/confirm every pending document if any in the licenses section.

You need:
- your apple developer account email
- an app-specific password generated at https://appleid.apple.com/account/manage, here the guide https://support.apple.com/en-us/HT204397
- the ProviderShortname  found with `xcrun altool --list-providers -u <email> -p <password>` with the aformentioned credentials

Then use the following `./afterSign.js`:

```javascript
const fs = require('fs');
const path = require('path');
const electron_notarize = require('electron-notarize');
const { build: { appId } } = require('./package.json');

module.exports = async params => {
    if (process.platform !== 'darwin')
        throw new Error('You can build MacOS .app only on MacOS.');

    const appPath = path.join(params.appOutDir, `${params.packager.appInfo.productFilename}.app`);
    if (appPath.includes('/dist/win')) {
        console.log(`skipping notarization for ${appPath}`);
        return;
    }

    if (!fs.existsSync(appPath))
        throw new Error(`Cannot find application at: ${appPath}`);

    console.log(`Notarizing ${appId} found at ${appPath}`);

    try {
        await electron_notarize.notarize({
            appBundleId: appId,
            appPath: appPath,
            appleId: 'xxx', // apple developer email
            appleIdPassword: 'xxx',
            ascProvider: 'xxxx',
        });
    }
    catch (error) {
        console.error(error);
    }

    console.log(`Done notarizing ${appId}`);
};
```

Hope this helps.

**Comment by mitchdennett** [comment]
Amazing! @damianobarbati  that worked great! I just needed to add the `ascProvider:` to my notarize script!

**Comment by pierotofy** [comment]
Confirm, it worked for me too. Thanks @damianobarbati .

**Comment by dart-sari** [comment]
Really nice. Helped me a lot! Thx
