### ISSUE TITLE
Error: Failed to upload:  XML document structures must start and end within the same entity.

### ISSUE THREAD

**Issue by AleksMeshkov** [electron/electron-notarize#50]
Hmm, very strange. 
Everything worked before. No new agreements to sign at developer.apple.com and appstoreconnect.apple.com.

Maybe it has something with installing the latest Catalina supplemental update?

Could someone test that please?

Os X: 10.15.6

"electron-builder": "^22.7.0" (also tried on 22.8.0)
"electron": "8.3.1"
"electron-notarize": "^1.0.0"

```
Error: Failed to upload app to Apple's notarization servers

2020-08-14 15:46:05.395 altool[4345:35320]  Error:
[2020-08-14 15:46:05 MSK] <main>  INFO: ParseError at [row,col]:[1824,2]
Message: XML document structures must start and end within the same entity. Exception's name: javax.xml.stream.XMLStreamException, Exception's message: ParseError at [row,col]:[1824,2]
Message: XML document structures must start and end within the same entity.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.apple.transporter.launcher.Application.start(Application.java:220)
        at com.apple.transporter.launcher.Application.main(Application.java:658)
Caused by: com.apple.transporter.bootstrap.BundleNotFoundException: bundle=[org.apache.felix.configadmin] version=[1.9.10,2.0.0) not found.
        at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:269)
        at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)
        at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)
        at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
        ... 6 more
2020-08-14 15:46:05.409 altool[4345:35320]  Out:
2020-08-14 15:46:05.423 altool[4345:35313] *** Error: Unable to notarize app.
2020-08-14 15:46:05.423 altool[4345:35313] *** Error: code -10000 (An error occurred uploading to the App Store.)

    at node_modules/electron-notarize/src/index.ts:87:13
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/electron-notarize/lib/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by AleksMeshkov** [comment]
I just tried to notarize another electronic project that remained untouched for about a month. Same error.
Next I

**Comment by AleksMeshkov** [comment]
Okay, most likely Apple had a bug. Now it works fine.
