### ISSUE TITLE
Notarization failure after upgrading electron-forge

### ISSUE THREAD

**Issue by tubbo** [electron/electron-notarize#90]
After upgrading Electron Forge to `v6.0.0-beta.61`, we got the following error in our CI:

```
Run yarn make
- Checking your system
✔ Checking your system
- Resolving Forge Config
✔ Resolving Forge Config
- Preparing to Package Application for arch: x64
We need to package your application before we can make it
- Compiling Main Process Code
✔ Compiling Main Process Code
- Compiling Renderer Template
✔ Compiling Renderer Template
- Compiling Renderer Preload: main_window
✔ Compiling Renderer Preload: main_window
✔ Preparing to Package Application for arch: x64
- Preparing native dependencies
✔ Preparing native dependencies
- Packaging Application
WARNING: Code sign failed; please retry manually. Error: No identity found for signing.

An unhandled rejection has occurred inside Forge:
Error: The appleId property is required when using notarization with appleIdPassword
    at Object.validateLegacyAuthorizationArgs (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/validate-args.ts:36:13)
    at authorizationArgs (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/legacy.ts:17:16)
    at Object.<anonymous> (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/legacy.ts:58:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/lib/legacy.js:4:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

My config in Electron Forge:

```javascript
const { APPLE_ID, APPLE_PASSWORD, APPLE_DEVELOPER_IDENTITY } = process.env

module.exports = {
  packagerConfig: {
    asar: true,
    icon: './src/icons/app.icns',
    extraResource: ['./src/sounds/[REDACTED].aif'],
    osxSign: {
      identity: APPLE_DEVELOPER_IDENTITY,
      'hardened-runtime': true,
      entitlements: 'etc/entitlements.plist',
      'entitlements-inherit': 'etc/entitlements.plist',
      'signature-flags': 'library',
      'gatekeeper-assess': false,
    },
    osxNotarize: {
      appBundleId: '[REDACTED]',
      ascProvider: '[REDACTED]',
      appleId: APPLE_ID,
      appleIdPassword: APPLE_PASSWORD,
    },
    packageManager: 'yarn',
    executableName: '[REDACTED]',
  },
```

This works when I don't upgrade `electron-forge` which means those environment variables are indeed set in my secrets.

**Comment by tubbo** [comment]
This is definitely an issue with `electron-packager`, actually. This diff shows what we did to workaround the problem:

```diff
diff --git a/package.json b/package.json
index 7a3e661..4baf096 100644
--- a/package.json
+++ b/package.json
@@ -197,5 +197,8 @@
     "ts-jest": "27.0.5",
     "twitch-embed": "1.1.4",
     "utility-types": "3.10.0"
+  },
+  "resolutions": {
+    "electron-packager": "15.3.0"
   }
 }
diff --git a/yarn.lock b/yarn.lock
index 3405330..df33e06 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -6297,7 +6297,7 @@ __metadata:
   languageName: node
   linkType: hard
 
-"asar@npm:^3.0.0, asar@npm:^3.1.0":
+"asar@npm:^3.0.0":
   version: 3.1.0
   resolution: "asar@npm:3.1.0"
   dependencies:
@@ -9379,7 +9379,7 @@ __metadata:
   languageName: node
   linkType: hard
 
-"electron-notarize@npm:^1.1.1":
+"electron-notarize@npm:^1.0.0":
   version: 1.1.1
   resolution: "electron-notarize@npm:1.1.1"
   dependencies:
@@ -9406,15 +9406,15 @@ __metadata:
   languageName: node
   linkType: hard
 
-"electron-packager@npm:^15.0.0":
-  version: 15.4.0
-  resolution: "electron-packager@npm:15.4.0"
+"electron-packager@npm:15.3.0":
+  version: 15.3.0
+  resolution: "electron-packager@npm:15.3.0"
   dependencies:
     "@electron/get": ^1.6.0
-    asar: ^3.1.0
+    asar: ^3.0.0
     cross-spawn-windows-exe: ^1.2.0
     debug: ^4.0.1
-    electron-notarize: ^1.1.1
+    electron-notarize: ^1.0.0
     electron-osx-sign: ^0.5.0
     extract-zip: ^2.0.0
     filenamify: ^4.1.0
@@ -9430,7 +9430,7 @@ __metadata:
     yargs-parser: ^20.0.0
   bin:
     electron-packager: bin/electron-packager.js
-  checksum: 7ffc94b89899742f2d910dd152802576a4f695a4703db745d71ddf43c438335c7dc0aeb72e2256d9a8e528250f2c2c7b70cf3095ec70c84ad5db04ad3b557cc7
+  checksum: f56f6e00612a3187ad7b3cfcd474bdbd50f1efb90bcd9cfc9d7174136215b5035d111983060365732c0d2c58fb2f5b44e7d853dcfb2a60891dd414586515c66d
   languageName: node
   linkType: hard
```
